# -*- coding: utf-8 -*-
"""01_add_two_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHEf7F7-TaE6_QFkB3UvL_zfblQwE5Cd

# Introduction to Python 🐍
 Python is a high-level interpreted programming language known for its simplicity and readability. It is widely used in web development data science artificial intelligence automation and more

#Features of Python:
Easy to Learn & Use  Python has a simple syntax similar to English.

Interpreted Language  No need for compilation; Python runs directly.

Dynamically Typed  You don't need to declare variable types.

Object-Oriented & Functional  Supports multiple programming paradigms.

Large Community & Libraries  Huge support and extensive libraries.
"""

def main():
    # Prompt the user to enter the first number
    num1 = int(input("Enter the first number: "))

    # Prompt the user to enter the second number
    num2 = int(input("Enter the second number: "))

    # Calculate the sum
    total = num1 + num2

    # Print the total sum
    print(f"The sum of {num1} and {num2} is: {total}")

# This provided line is required at the end of
# the Python file to call the main() function.
if __name__ == '__main__':
    main()